// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Fxs2c13NCBDMI3ZDBw8xy7i7CihTdUY',
    appId: '1:82302935172:web:3837b9ebac88ae83fde2d1',
    messagingSenderId: '82302935172',
    projectId: 'pet-friend-2d286',
    authDomain: 'pet-friend-2d286.firebaseapp.com',
    storageBucket: 'pet-friend-2d286.appspot.com',
    measurementId: 'G-VEEMSPB484',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYVUHkBjm_XVkWnkTDC0n4cEJVBEQNd1o',
    appId: '1:82302935172:android:d7254fd4b99dae33fde2d1',
    messagingSenderId: '82302935172',
    projectId: 'pet-friend-2d286',
    storageBucket: 'pet-friend-2d286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFr2r02JaNrLQj1BuBQxlt7Wr8ChTpEHE',
    appId: '1:82302935172:ios:f71af2b4a862f868fde2d1',
    messagingSenderId: '82302935172',
    projectId: 'pet-friend-2d286',
    storageBucket: 'pet-friend-2d286.appspot.com',
    iosClientId: '82302935172-7vtdvl0o1aeql4e09ufr6hsvd50ej7uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.petFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFr2r02JaNrLQj1BuBQxlt7Wr8ChTpEHE',
    appId: '1:82302935172:ios:f71af2b4a862f868fde2d1',
    messagingSenderId: '82302935172',
    projectId: 'pet-friend-2d286',
    storageBucket: 'pet-friend-2d286.appspot.com',
    iosClientId: '82302935172-7vtdvl0o1aeql4e09ufr6hsvd50ej7uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.petFriend',
  );
}
